# Common formulae
[
  "bash",
  "curl",
  "gh",
  "git",
  "git-lfs",
  "libxml2",
  "neovim",
  "nvm",
  "pyenv",
  "ripgrep",
  "rustup",
  "tmux",
  "tmuxinator",
  "tree",
  "unzip",
  "uv",
  "wget"
].each { |pkg| brew pkg }

# macOS-only casks
if OS.mac?
  [
    "font-jetbrains-mono-nerd-font",
    "ghostty",
    "google-chrome",
    "karabiner-elements",
    "tailscale-app",
    "unnaturalscrollwheels"
  ].each { |c| cask c }
end
