import = ["~/.config/alacritty/themes/themes/catppuccin_frappe.toml"]


[font]
size = 18

[window]
startup_mode = "Maximized"
decorations = "none"

[window.padding]
x = 0
y = 0

[env]
  TERM = "xterm-256color"
