brew 'colima'
brew 'curl'
brew 'docker'
brew 'docker-compose'
brew 'git'
brew 'neovim'
brew 'nvm'
brew 'ripgrep'
brew 'tmux'
brew 'tree'
brew 'unzip'
brew 'wget'
cask 'firefox'
cask 'font-jetbrains-mono-nerd-font'
cask 'karabiner-elements'
cask 'unnaturalscrollwheels'

